### ISSUE TITLE
Gutter does not work with acrylic look

### ISSUE THREAD

**Issue by TheHugeManatee** [moyicat/inkdrop-code-fold#4]
When using the Vibrant Dark UI theme with translucency enabled, the folding gutter is opaque.

Was able to resolve it by adding this to my custom style sheet:
```css
.CodeMirror-gutters {
    background-color: rgba(0,0,0,0) !important
}
```

No idea if this would interfere other themes, but thought I'd leave it here in case someone else is looking for a solution.

before:
![grafik](https://user-images.githubusercontent.com/2657288/133404590-a47a4956-3666-41fe-82a3-bc1872ab6fd1.png)

after:
![grafik](https://user-images.githubusercontent.com/2657288/133404671-65ab1e6a-8a36-44b5-956c-174fc2856e9c.png)
